# This file stores configurations for your Shopify app.

scopes = "read_products,read_customers,read_orders,read_locales,read_content,read_script_tags,read_themes,write_themes,write_script_tags,write_products,write_customers,write_orders"
